### ISSUE TITLE
Package subpath './lib/tokenize' is not defined by "exports"

### ISSUE THREAD

**Issue by tomaszwojciechowski** [bahmutov/taste-the-sauce#1]
`C:\Users\x\WebstormProjects\taste-the-sauce>npm start   

> taste-the-sauce@1.0.0 start
> react-scripts start

node:internal/modules/cjs/loader:571
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\postcss-safe-parser\node_modules\postcss\package.json
    at new NodeError (node:internal/errors:399:5)
    at exportsNotFound (node:internal/modules/esm/resolve:361:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:697:9)
    at resolveExports (node:internal/modules/cjs/loader:565:36)
    at Module._findPath (node:internal/modules/cjs/loader:634:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1061:27)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\postcss-safe-parser\lib\safe-parser.js:1:17) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v18.15.0`

**Comment by bahmutov** [comment]
Hi @tomaszwojciechowski 
Can you try to start the app using Node v16? I wonder why react scripts is failing like this.

**Comment by tomaszwojciechowski** [comment]
For now, I deleted node_modules folder and package-lock.json, and receives:

`C:\Users\x\WebstormProjects\taste-the-sauce>npm start   

> taste-the-sauce@1.0.0 start
> react-scripts start

i ｢wds｣: Project is running at http://192.168.3.23/
i ｢wds｣: webpack output is served from
i ｢wds｣: Content not from webpack is served from C:\Users\x\WebstormProjects\taste-the-sauce\public
i ｢wds｣: 404s will fallback to /
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:471:10)
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:503:5
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:358:12
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at iterateNormalLoaders (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:221:10)
C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\react-scripts\scripts\start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\util\createHash.js:135:53)
    at NormalModule._initBuildHash (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:417:16)
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:452:10
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\webpack\lib\NormalModule.js:323:13
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\babel-loader\lib\index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.15.0`

**Comment by bahmutov** [comment]
I pushed new branch to the repo https://github.com/bahmutov/taste-the-sauce/tree/bump-react-scripts Could you check it out, install dependencies, and try starting the app, please?

```
git pull
git checkout bump-react-scripts
npm install
npm start
```

**Comment by tomaszwojciechowski** [comment]
`C:\Users\x\WebstormProjects\taste-the-sauce>npm start

> taste-the-sauce@1.0.0 start
> react-scripts start

Starting the development server...
Failed to compile.

Error: error:0308010C:digital envelope routines::unsupported
    at String.replace (<anonymous>)
ERROR in ./src/assets/svg/close@3x.svg
Module build failed (from ./node_modules/file-loader/dist/cjs.js):
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at String.replace (<anonymous>)
    at interpolateName (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\loader-utils\lib\interpolateName.js:110:8)
    at Object.loader (C:\Users\x\WebstormProjects\taste-the-sauce\node_modules\file-loader\dist\index.js:29:48)

webpack compiled with 2 errors
`

**Comment by bahmutov** [comment]
What about using Node v16?

**Comment by bahmutov** [comment]
Ok, I pushed new change to this branch, can you try that? This is because of https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported

**Comment by tomaszwojciechowski** [comment]
Now works with Node 18 :)

**Comment by bahmutov** [comment]
ok, unfortunately to have it working with Node 16 and 18, got to pass option but only when running in Node v18, so in the package.json I have

```json
{
  "scripts": {
    "start": "react-scripts start",
    "start-18": "react-scripts --openssl-legacy-provider start"
  }
}
```

**Comment by tomaszwojciechowski** [comment]
To successfully start application with Node 18, I used "npm start" not "npm start-18", and it worked?

**Comment by bahmutov** [comment]
Are you sure, try `localhost:3000` to see if it throws an error loading SVG

**Comment by bahmutov** [comment]
I have another repo that is checking the answers on CI and I have test jobs for Node v16 and Node v18 using `npm start` and `npm run start-18` respectively and they are green. I have updated lessons branches and lesson contents, so hope it all is good now.
